### PR TITLE
add group management methods to client

### PR DESCRIPTION
**Pull request by mhilton**
Add SetUserGroups and ModifyUserGroups to the client.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/idmclient/86/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/idmclient/87/
Test PASSed.

**Comment by urosj** [comment]
LGTM, no QA, but we'll do that later.

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/idmclient-merge

**Pull request merged**
