### PR TITLE
move to gopkg.in/juju/idmclient.v1

### PR DESCRIPTION
**Pull request by rogpeppe**
Also change to use gopkg.in/httprequest.v1.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/idmclient/128/

**Review by mhilton — APPROVED** [review]
LGTM

**Review by alesstimec — APPROVED** [review]

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/idmclient/129/

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/idmclient-merge

**Pull request merged**
