### PR TITLE
Use names.v2

### PR DESCRIPTION
**Pull request by wallyworld**
Update to use gopkg.in/names.v2

Pull in some updated dependencies also.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/idmclient/66/
Test PASSed.

**Comment by axw** [comment]
LGTM, but is this part of any release yet? Do we need a new branch?

**Comment by wallyworld** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/idmclient-merge

**Pull request merged**
