### PR TITLE
ussologin: Change the form keys

### PR DESCRIPTION
**Pull request by mattyw**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/idmclient/30/
Test PASSed.

**Comment by mhilton** [comment]
:+1:

**Comment by mattyw** [comment]
:shipit:

**Comment by mattyw** [comment]
$$merge$$

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/idmclient-merge

**Pull request merged**
