### PR TITLE
all: update macaroon bakery to v2-unstable

### PR DESCRIPTION
**Pull request by mhilton**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/idmclient/68/
Test PASSed.

**Comment by rogpeppe** [comment]
LGTM, although I'm not entirely sure about putting arbitrary binary data in a form parameter.

**Comment by urosj** [comment]
👍

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/idmclient-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/idmclient/69/
Test PASSed.

**Pull request merged**
