### PR TITLE
params: add last_login and last_discharge parameters

### PR DESCRIPTION
**Pull request by mhilton**
Add support for LastLogin and LastDischarge times.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/idmclient/91/
Test PASSed.

**Comment by rogpeppe** [comment]
LGTM except for the omitempty thing.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/idmclient/92/
Test PASSed.

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/idmclient-merge

**Pull request merged**
