### PR TITLE
idmclient: add GroupCache

### PR DESCRIPTION
**Pull request by rogpeppe**
This will allow the charmstore to use PermChecker and also use the
same cache to fetch groups when it needs to.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/idmclient/55/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/idmclient/56/
Test PASSed.

**Comment by alesstimec** [comment]
LGTM

**Comment by mhilton** [comment]
:+1:

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/idmclient-merge

**Pull request merged**
