### PR TITLE
rename the identity repository idmclient.

### PR DESCRIPTION
**Pull request by mhilton**
Also move the idmclient package to the top level.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/identity/18/
Test PASSed.

**Comment by rogpeppe** [comment]
LGTM

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/idmclient-merge

**Pull request merged**
